"""add User model

Revision ID: fd88490f222b
Revises: 
Create Date: 2024-01-24 04:27:41.446461

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fd88490f222b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_user',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('email', sa.String(length=255), nullable=False),
                    sa.Column('password_hash', sa.String(length=100), nullable=False),
                    sa.Column('registered_on', sa.DateTime(), nullable=True),
                    sa.Column('admin', sa.Boolean(), nullable=True),
                    sa.Column('public_id', sa.String(length=36), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    sa.UniqueConstraint('public_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_user')
    # ### end Alembic commands ###
